---
# tasks file for ansible-role-openio-netdata

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: "Configure repositories for {{ ansible_os_family }} distribution"
  tags:
    - install
  include : "{{ ansible_os_family }}.yml"

- name: 'Netdata: Install packages'
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ netdata_packages }}"

- name: Install OpenIO plugins for netdata
  unarchive:
    # TODO: make compatible with facter_architecture
    src: https://github.com/vdombrovski/openio-netdata/releases/download/v{{netdata_openio_plugins_version}}/openio-netdata-{{netdata_openio_plugins_version}}.amd64.tar.gz
    dest: "{{ netdata_openio_plugins_endpoint }}"
    remote_src: yes

# A filter would be much better here @cdelgehier ;-)
- name: Register OpenIO RAW-X services configured
  shell: ls -d /etc/oio/sds/*/rawx-*||true
  register: netdata_openio_rawxlogs
  changed_when: false
- name: Register OpenIO directory services configured
  shell: ls -d /etc/oio/sds/*/meta*||true
  register: netdata_openio_metalogs
  changed_when: false
- name: Creating service list to monitor
  set_fact:
    netdata_openio_service_rawx: |
      [{% for item in netdata_openio_rawxlogs.stdout_lines -%}
        ["{{ item| regex_replace('/etc/oio/sds/(\w+)/.*', '\1') }}","{{ item|regex_replace('/etc/oio/sds/\w+/(\w+)-\w+', '\1') }}","{{ item|regex_replace('/etc/oio/sds/\w+/\w+-(\w+)', '\1') }}"],
      {%- endfor %}]
    netdata_openio_service_meta: |
      [{% for item in netdata_openio_metalogs.stdout_lines -%}
        ["{{ item| regex_replace('/etc/oio/sds/(\w+)/.*', '\1') }}","{{ item|regex_replace('/etc/oio/sds/\w+/(\w+)-\w+', '\1') }}","{{ item|regex_replace('/etc/oio/sds/\w+/\w+-(\w+)', '\1') }}"],
      {%- endfor %}]

- name: "Get beanstalk instance data"
  shell: "gridinit_cmd status2 | grep beanstalk"
  register: netdata_openio_tmp_beanstalk

- name: "Register beanstalk services"
  set_fact:
      netdata_openio_service_beanstalk: |
        [{% for item in netdata_openio_tmp_beanstalk.stdout_lines -%}
          ["{{ item | regex_replace('^(.*?) .*', '\1')}}", "{{ item | regex_replace('.* -l (.*?) .*', '\1')}}", "{{ item | regex_replace('.* -p (.*?) .*', '\1')}}"]
        {%- endfor %}]

- name: "Get redis instance data"
  shell: "ps aux | grep redis | grep -v \"grep\\|sentinel\" | awk '{print $NF}'"
  register: netdata_openio_service_redis

- name: 'Netdata: Set configurations'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode:  0644
  with_items:
    - { src: "{{ netdata_global_conf_template }}", dest: "{{ netdata_global_conf_path }}" }
    - { src: "{{ netdata_weblog_conf_template }}", dest: "{{ netdata_weblog_conf_path }}" }
    - { src: "{{ netdata_python_d_conf_template }}", dest: "{{ netdata_python_d_conf_path }}" }
    - { src: "{{ netdata_apps_groups_conf_template }}", dest: "{{ netdata_apps_groups_conf_path }}" }
    - { src: "{{ netdata_beanstalk_conf_template }}", dest: "{{ netdata_beanstalk_conf_path }}" }
    - { src: "{{ netdata_redis_conf_template }}", dest: "{{ netdata_redis_conf_path }}" }
  notify:
    - restart netdata

- name: 'Netdata: Start service'
  service:
    name: "{{ netdata_service_name }}"
    state: started
    enabled: true
